# Site settings
title: Carmetry brand guidelines
email: info@carmetry.com
description: > # this means to ignore newlines until "baseurl:"
  Carmetry brand guidelines, internal use only.
baseurl: "/brand-guidelines" # the subpath of your site, e.g. /blog
url: "https://carmetry.github.io/brand-guidelines/" # the base hostname & protocol for your site
twitter_username: CarmetryApp
github_username:  carmetry

# Build settings
markdown: kramdown
